### PR TITLE
sync rules lists with the order used in hashcat OpenCL/inc_rp.h

### PR DESCRIPTION
**Pull request by roycewilliams**
* Synced rules lists with OpenCL/inc_rp.h for maintainability.
* Expanded the is_supported() regex with /x for readability.
* Fixed minor typo.

### CODE REVIEW

**Comment by roycewilliams** [comment]
Note also that the 'e' rule is new and pending hashcat's next release - like E, but with a custom separator instead of assuming space.

**Comment by mhasbini** [comment]
@roycewilliams Thanks!

**Comment by roycewilliams** [comment]
I just noticed that this commit appears to have broken the build, but I don't immediately see what the root cause is.

**Comment by mhasbini** [comment]
The failing tests in `t/01.dups.t` aren't caused by this commit.

It's a bug with keeping history after applying some rules. I'm working on
it :+1:

**Pull request merged**
